uber/streetscape.gl

- modules/layers/src/sign-layer/sign-layer.js
Accessing the attributeManager through `this.state` is deprecated
and is causing an issue with the latest deck.gl.
Change to use the accessor function and the issue went away.
> Fix issue with attributeManager not being defined

- modules/core/src/index.js
- modules/core/src/utils/style.js
Exporting `mergeXVIZStyles` so that it can be used in external projects.
> Export mergeXVIZStyles

- docs/get-started/starter-kit.md
For https://github.com/uber/streetscape.gl/issues/257
> Fix missing link to XVIZ example server

- docs/api-reference/xviz-loader-interface.md
- modules/core/src/components/declarative-ui/xviz-metric.js
- modules/core/src/components/playback-control/index.js
- modules/core/src/loaders/xviz-file-loader.js
- modules/core/src/loaders/xviz-live-loader.js
- modules/core/src/loaders/xviz-loader-interface.js
- modules/core/src/loaders/xviz-stream-loader.js
- modules/core/src/loaders/xviz-websocket-loader.js
- test/modules/core/loaders/xviz-live-loader.spec.js
- test/modules/core/loaders/xviz-stream-loader.spec.js
- Make `streamBuffer` mandatory; automatically construct `StreamSynchronizer` instance
- Added `onXVIZMessage` method for shared logic; hooks for subclassing
- Decouple `getCurrentFrame` from `getStreams` (perf)
- Renamed a few confusing selectors:
+ `getBufferRange` -> `getBufferedTimeRanges`
+ `getBufferStart` -> `getBufferStartTime`
+ `getBufferEnd` -> `getBufferEndTime`
> Simplify XVIZLoaderInterface

- modules/core/src/components/log-viewer/constants.js
- modules/core/src/components/log-viewer/core-3d-viewer.js
For https://github.com/uber/xviz/issues/402
Default light positions are in METER_OFFSET coordinate system but did not explicitly state so. At runtime, it falls back to the layer's coordinate system, resulting in an exception when GEOGRAPHIC coordinates are used.
> Fix light settings coordinate system

- Dockerfile
This will be based on a supported version of debian and fix the Buildkite errors.
> Update docker tests to newer version of Node

- modules/core/src/loaders/xviz-loader-interface.js
- test/modules/core/loaders/index.js
- test/modules/core/loaders/xviz-loader-interface.spec.js
The XVIZLoaderInterface already expects the object streamBuffer
to exist, it should propagate the seek() to the streamBuffer so it
may do with that event as it needs.  In most cases, manage data
appropriately based on the current playhead.
> Make the XVIZLoaderInterface propogate seek() to the streamBuffer

- modules/layers/src/sign-layer/README.md
- modules/layers/src/sign-layer/sign-layer-vertex.glsl.js
The signs were flipped after #281. Also clarifying in documentation what `angle` is.
> [layers] Flip signs

- dev-docs/viewer-app.md
- test/apps/viewer/README.md
- test/apps/viewer/index.html
- test/apps/viewer/package.json
- test/apps/viewer/src/app.js
- test/apps/viewer/src/constants.js
- test/apps/viewer/src/log-from-factory.js
- test/apps/viewer/webpack.config.js
Rather than construct with fix parameters, allow the getting-started
to use the URL determine which data is loaded.
Default behavior w/o a URL path is the same, but if a path is provided
the stream and live loaders will construct their request using the url
path and params
Supports loading multiple logs easily and is useful for testing.
- Pass the URL path as part of the **serverUrl** in the server config
- Support the following query parameters mapped to XVIZLoader options
- log
- server
- profile
- timestamp
- duration
- worker
> Add URL passing to the XVIZ Loaders

- modules/core/package.json
- yarn.lock
This fixes a performance issue related to large props beings
serialized unnecessarily.
> Upgrade to deck.gl 6.4.10

- modules/core/src/components/declarative-ui/image-sequence.js
When a new JPEG encoded frame is transmitted via XVIZ the video
display jumps to a black image for a split second before the new
actual image is drawn. This commit prevents redrawing of the video
image while a (decoding?) promise is pending.
> Fix black video image being drawn while image promise is pending

- modules/core/src/debug/constants.js
- modules/core/src/debug/log-viewer-stats.js
- modules/core/src/debug/xviz-workers-monitor.js
- modules/core/src/debug/xviz-workers-status.js
- modules/core/src/index.js
- modules/core/src/loaders/xviz-file-loader.js
- modules/core/src/loaders/xviz-websocket-loader.js
- test/apps/viewer/src/app.js
- test/apps/viewer/src/constants.js
Added a new debug panel with `@xviz/parser`worker farm status + `LogViewer` stats chart:
Note:  an `XVIZWorkersMonitor` instance (called `monitor`) keeps track of the XVIZ worker farm status. When `monitor.update()` is called, the workers status gets updated. This method is passed as a callback to `@xviz/parser`'s `parseStreamMessage` via the `debug` callback argument. When the debug callback is called, the XVIZ workers status are updated in the monitor. This allows us to decorrelate the rate at which the monitor workers status gets updated (on each message by  `parseStreamMessage`) from the rate at which a view component is updated (here `XvizWorkersStatus` via the monitor's `reportCallback`). We don't want the view component to re-render on every incoming un-parsed XVIZ message, this …
> New debug panel with XVIZ Parser and Log Viewer stats

- modules/core/src/components/log-viewer/core-3d-viewer.js
> Fix debug callback of LogViewer

- modules/core/src/components/stream-settings-panel.js
- test/modules/core/components/stream-settings-panel.spec.js
This makes dealing with larges numbers of stream more manageable.
It only allows for collapsing the first level, but that is a great start.
> Support collapsing in stream settings panel

- modules/core/src/components/log-viewer/core-3d-viewer.js
Previously only xviz layers where sorted by z-index. Now it's possible
to set the property zIndex on a custom layer and have it rendered
before a xviz layer.
> Sort xviz- and custom-layers together by z-index

- examples/get-started/README.md
Point users to the Starter Kit instruction docs.
> Add new link that points to docs relating to running the Starter Kit

- modules/core/src/components/declarative-ui/xviz-metric.js
At the moment, `isLoading` is checking to see if there is a `currentTime` in order to determine whether or not to display a metric. As `currentTime` is declared but does not have a value (until it's passed in as a prop) it needs to be checked against `undefined` as well.
> Update the isLoading variable to check against undefined and null values

- examples/get-started/src/app.js
- test/apps/viewer/src/app.js
KITTI data in the getting-started app was showing `Fri, 16 Jan 1970 05:50:42 GMT` instead of `Mon, 26 Sep 2011 13:04:32 GMT`
The website demo app correctly scales the time, but is hard coded for the data and not the XVIZ config.
> Fix timestamp display in playback control

- docs/api-reference/connect-to-log.md
- docs/api-reference/log-viewer.md
- docs/api-reference/xviz-loader-interface.md
- docs/api-reference/xviz-metric.md
- docs/api-reference/xviz-plot.md
- docs/api-reference/xviz-video.md
- modules/core/src/components/declarative-ui/xviz-metric.js
- modules/core/src/components/declarative-ui/xviz-plot.js
- modules/core/src/components/declarative-ui/xviz-video.js
- modules/core/src/components/hud/base-widget.js
- modules/core/src/components/log-viewer/core-3d-viewer.js
- modules/core/src/components/log-viewer/index.js
- modules/core/src/components/log-viewer/object-labels-overlay.js
- modules/core/src/components/stream-settings-panel.js
- modules/core/src/loaders/xviz-loader-interface.js
- modules/core/src/utils/metrics-helper.js
- test/modules/core/utils/metrics-helper.spec.js
- Add `getStreamMetadata` to `XVIZLoaderInterface`
- Build local stream metadata if `DYNAMIC_STREAM_METADATA` config is set (requires https://github.com/uber/xviz/pull/493)
- Switch core components to use `getStreamMetadata` instead of `getMetadata().streams`
> Support dynamic stream metadata

- docs/api-reference/connect-to-log.md
- docs/api-reference/xviz-metric.md
- docs/api-reference/xviz-plot.md
- modules/core/package.json
- modules/core/src/components/declarative-ui/missing-data-card.js
- modules/core/src/components/declarative-ui/xviz-metric.js
- modules/core/src/components/declarative-ui/xviz-plot.js
- modules/core/src/utils/metrics-helper.js
This PR addresses [issue 344](https://github.com/uber/streetscape.gl/issues/344). 
- Adds in a Missing Data component to let users know which information is missing
- Missing data has a Tooltip and ellipsis applied to it
- Moves the conditional logic of displaying a loading spinner out of Monochrome (MetricCard) and into the XVIZ layer 
- Bumps up the Monochrome version to beta.4
> Add missing stream data component

- docs/api-reference/connect-to-log.md
- modules/core/src/components/declarative-ui/xviz-panel.js
- modules/core/src/components/declarative-ui/xviz-plot.js
- modules/core/src/components/declarative-ui/xviz-table.js
- modules/core/src/utils/transform.js
protobuf.js instances use prototype construction and properties will be searched up the prototype chain.  We must add validation to ensure the property is on the instance and not the prototype.
> Protobuf related changes due to using protobufjs objects

- modules/core/src/components/declarative-ui/xviz-panel.js
I'm validating why local testing didn't show this.  Possible metadata was present by the time this rendered locally?
> Fix bug where panel is undef on first render due to no metadata

- .prettierignore
- examples/website-demo/src/custom-styles.js
- examples/xviz-playground/package.json
- examples/xviz-playground/webpack.config.js
- modules/core/src/utils/transform.js
- ignore lint on some vendor files
- website-demo: change strings to conform to spec as uppercase
- playground: fix build dependency on @babel/preset-flow
- core: fix for missing 'links' in transform path
> Various fixes

- examples/get-started/src/constants.js
- examples/xviz-playground/src/code-samples.js
- modules/core/src/layers/point-cloud-layer/point-cloud-layer.js
- test/apps/viewer/src/constants.js
'point_color_mode' should be uppercase and the corresponding xviz change
is https://github.com/uber/xviz/pull/559
> Adjust 'point_color_mode' changing to upperCase

- modules/layers/src/lane-layer/lane-layer.js
There is no padding in the front of the array, so makes the start ratio
calculation ignore the last point which was causing an undefined value
to be used resulting in an exception being thrown.
> Fix lane-layer issue due to path-layer position data change

- modules/core/src/index.js
- modules/core/src/loaders/loader-interface.js
- modules/core/src/loaders/playable-loader-interface.js
- modules/core/src/loaders/xviz-loader-interface.js
Split up `XVIZLoaderInterface` into sub classes to introduce more modular interfaces.
* `LoaderInterface`: responsible for holding state of the loaded data.
* `PlayableLoaderInterface`: exposes the methods required for compatibility with the `PlaybackControl` streetscape component - that enables scrubbing through a buffered log.
```
/**
* This class defines the interface for Loader classes. A Loader is factually
* a store holding state for connected components. We call the subclasses of this
* interface "Loaders" and not simply "Stores" because they are is usually also
* responsible for loading data in addition of storing it.
*
* The pattern of a Loader is very similar to the Redux store.
* We provide a "connect()" High Order Component (H.O.C.) to connect React
* components to Loader …
```
> New loader interfaces
