docs/about-avs.md, docs/api-reference/log-viewer.md, modules/core/src/components/log-viewer/index.js
For https://github.com/uber/streetscape.gl/issues/248
=> Add onClick callback

examples/get-started/package.json, examples/get-started/src/app.js, examples/get-started/src/constants.js, examples/website-demo/package.json, examples/xviz-playground/package.json, modules/core/src/components/declarative-ui/xviz-plot.js, modules/core/src/components/stream-settings-panel.js
Example:
- Bump dependency version to beta
- Render all declarative UI panels
- Add stream settings
Component bug fixes:
- XVIZPlot: show spinner if data is not available
- StreamSettingsPanel: some streams show "undefined" as type
=> Update get-started example

docs/README.md, docs/get-started/starter-kit.md
=> Fix doc get-started source code links and spelling

docs/api-reference/xviz-loader-interface.md, docs/api-reference/xviz-metric.md, modules/core/src/components/declarative-ui/xviz-metric.js, modules/core/src/components/declarative-ui/xviz-video.js, modules/core/src/loaders/xviz-loader-interface.js, modules/core/src/utils/metrics-helper.js, test/modules/core/utils/metrics-helper.spec.js
Instead of filtering all streams, we only filter them when they are used.
=> Improve metrics perf

docs/get-started/starter-kit.md, test/index.js, test/website.js
This fixes 3 links and adds a home rolled test for broken links.  This
is something that should be in ocular as a build error.
=> Fix broken doc links and add test

examples/xviz-playground/src/auto-complete.js, examples/xviz-playground/src/editor.js, examples/xviz-playground/src/eval.js
=> Add auto-completion to xviz playground

examples/xviz-playground/index.html, examples/xviz-playground/src/editor.js, examples/xviz-playground/src/eval.js, examples/xviz-playground/src/timeline.js, examples/xviz-playground/src/xviz-json-loader.js, examples/xviz-playground/webpack.config.js
- JSON is editable
- Display message history on the timeline
=> [XVIZ-playground] allow editing JSON

modules/core/src/components/log-viewer/core-3d-viewer.js, modules/layers/src/sign-layer/sign-layer-fragment.glsl.js, modules/layers/src/sign-layer/sign-layer-vertex.glsl.js, modules/layers/src/sign-layer/sign-layer.js
For https://github.com/uber/streetscape.gl/issues/265
=> Fix sign layer orientation

docs/api-reference/log-viewer.md, modules/layers/src/imagery-layer/grid-geometry.js, modules/layers/src/imagery-layer/imagery-layer-vertex.js, modules/layers/src/imagery-layer/imagery-layer.js, modules/layers/src/sign-layer/sign-layer-fragment.glsl.js, modules/layers/src/sign-layer/sign-layer-vertex.glsl.js, modules/layers/src/traffic-light-layer/traffic-light-layer-fragment.glsl.js, modules/layers/src/traffic-light-layer/traffic-light-layer-vertex.glsl.js, modules/layers/src/traffic-light-layer/traffic-light-layer.js, test/apps/layers/index.html, test/apps/layers/package.json, test/apps/layers/src/app.js, test/apps/layers/src/constants.js, test/apps/layers/src/custom-layers.js, test/apps/layers/src/log-from-file.js, test/apps/layers/webpack.config.js, test/apps/webpack.config.local.js
Add a test app for layer debugging
=> Fix custom layers under deck.gl v7

examples/get-started/src/app.js
Now that we spin off the test application, go back to the simpler version of the example
=> Simplify get-started app

.buildkite/pipeline.yml, Dockerfile, docker-compose.yml, ocular-dev-tools.config.js, package.json, yarn.lock
=> Update CI setup: fix coverage report and browser test

modules/core/package.json, modules/core/src/components/log-viewer/core-3d-viewer.js, modules/core/src/layers/xviz-layer.js, yarn.lock
Per discussion in uber/streetscape.gl#305
Requires https://github.com/uber/xviz/pull/442
=> Handle new point cloud format

modules/core/package.json, yarn.lock
yarn.lock was not updated correctly
=> Monochrome beta 3

website/src/components/features.js
Not sure what changed, the website image is not correctly scaled.
=> Fix website styling

modules/core/src/utils/viewport.js
=> Disable double-click zoom transition

modules/core/src/components/stream-settings-panel.js, test/modules/core/components/stream-settings-panel.spec.js
Add collapse prop to stream settings panel docs
=> Stream settings panel doc update

modules/core/src/loaders/xviz-live-loader.js, modules/core/src/loaders/xviz-stream-loader.js, test/apps/viewer/src/app.js, test/modules/core/loaders/xviz-live-loader.spec.js, test/modules/core/loaders/xviz-stream-loader.spec.js
This enables the XVIZ source in the server to respond to option changes
through the URL query parameters.
=> Ensure query params from viewer are passed through to server request

docs/get-started/starter-kit.md
Fix broken link by adding the correct directory structure to the path
=> Fix broken link for issue 266

docs/api-reference/connect-to-log.md
Addresses issue #350 to correct the `connectToLog` docs (as well as a minor wording update).
=> Update connectToLog docs

modules/core/src/components/log-viewer/core-3d-viewer.js, modules/core/src/utils/memoize.js
Cache the result of expensive calculations
=> LogViewer minor perf improvement

modules/core/package.json, modules/layers/package.json, modules/main/package.json
=> Drop package engine requirements

modules/core/package.json, package.json, website/webpack.config.js, yarn.lock
- Bump ocular-dev-tools
- Faster pre-commit checks
- Fix website build script
- Use prod version dependency
=> Misc package setup fixes 

modules/core/src/layers/point-cloud-layer/point-cloud-layer-vertex.glsl.js, modules/core/src/layers/point-cloud-layer/point-cloud-layer.js
Align with deck.gl@>=7.2's uniforms and shader hooks
=> Upgrade PointCloudLayer vertex shader

modules/core/package.json
=> Restrict react-map-gl version

modules/core/src/loaders/loader-interface.js, modules/core/src/loaders/playable-loader-interface.js, modules/core/src/loaders/xviz-loader-interface.js
Because @twojtasz is ⚡ and merged #486  really fast 🤪
=> New loader interfaces take 2

modules/layers/package.json
Fix the "ell" in the minor version to be a "one".
Fixes #452.
=> Fix @deck.gl/layers version in modules/layers/package.json
